import os

def create_plugins():
    # delete previous plugins file and create a new
    if os.path.exists('./plugins.py'):
        os.remove('./plugins.py')

    plugins = '# this is an autogenerated file\n\n'

    if not os.path.exists('./plugins'):
        os.mkdir('plugins')

    for plugin_folder in os.listdir('plugins'):
        with open('./plugins/{0}/main.py' . format(plugin_folder)) as plugin:
            plugins = plugins + ''.join(plugin.readlines()) + '\n\n'

    with open('./plugins.py', 'w+') as plugins_file:
        plugins_file.write(plugins)
        plugins_file.close()

def run():
    from tokusentai import Tokusentai

    bot = Tokusentai()
    bot.run(os.getenv('TOKEN'))
